application: tough-variety-126419
version: 6
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: .*
  script: checkin.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: PIL
  version: latest

skip_files:
    - lib/PIL*


builtins:
- remote_api: on
- deferred: on

# inbound_services:
# - warmup
#
# instance_class: F4_1G
# automatic_scaling:
#  min_idle_instances: 1
#  max_idle_instances: automatic  # default value
#  min_pending_latency: 30ms  # default value
#  max_pending_latency: automatic
#  max_concurrent_requests: 50
